     VERSION    6     Fri May 24 08:39:04 2002                                  
      DESCR   Nickel template                                                   
    HSTRY  1 EXPEDT  Win32  May 24 10:46:28 2002 P PH        LA  O              
  DSGL CDAT1  DRAD ARAD NOFO                                                    
  GNLS CDAT1  MXCY  3                                                           
 AFAC NI    12.8376 3.8785 7.2920  .2565 4.443812.1763 2.380066.3421 1.0341 RHF 
 AFAC NI   M -.0172 35.739  .3174 14.269  .7136  4.566  .0000   .000 -.0143     
 AFAC NI   N 1.0302 12.252 1.4669  4.745  .4521  1.744  .0000   .000  .0036 2.00
 AFAC NI_     58.71  1.03         4.5                                           
 AFAC NI_SIZ      1.45      1.25 2.10   78                                      
 AFAC NI_XAB  14190  8942  4759  4604  2370                                     
 AFAC NI_XAN  -.956 1.036-1.343  .769-2.956  .509  .285 1.113  .261  .724       
 EXPR  HTYP1  PNTD                                                              
 EXPR  NATYP    1                                                               
 EXPR  NHST     1                                                               
 EXPR ATYP 1  NI          1      1.45      1.25 2.10   78                       
 EXPR NPHAS     1    0    0    0    0    0    0    0    0                       
CRS1    PNAM  Nickel                                                            
CRS1   ABSCO  1298.53   818.28   435.50   421.31   216.88     0.00     0.41     
CRS1   ATYPS    1                                                               
CRS1   F000      4.120   111.950                                                
CRS1   FRML1NI          4.00                                                    
CRS1   NATOM    1                                                               
CRS1  ABC     3.522600  3.522600  3.522600    N    0                            
CRS1  ANGLES   90.0000   90.0000   90.0000                                      
CRS1  AT  1A  NI        0.000000  0.000000  0.000000  1.000000NI1        4 000  
CRS1  AT  1B  0.025000                                                    I     
CRS1  AT  1C    430.00     2.639     3.364     1.642     0.491      5.20      28
CRS1  CELVOL    43.711                                                          
CRS1  DENSTY     8.920                                                          
CRS1  SG SYM  F m 3 m                                                           
CRS1  SPAXIS    0    0    1                                                     
HAP1 1 ZONE     0    0    0    0                                                
HAP1 1EXTPOW    0.00000E+00    N    0                                           
HAP1 1NAXIS     1                                                               
HAP1 1PHSFR      1.0000        N    0                                           
HAP1 1MECPRO     13.30     199.5     0.312                                      
HAP1 1PRCF      3   21   0.00500                                                
HAP1 1PRCF 1   0.425565E+00   0.263286E-01   0.296905E-01   0.404614E+02        
HAP1 1PRCF 2   0.404614E+02   0.000000E+00   0.000000E+00   0.529470E+01        
HAP1 1PRCF 3   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HAP1 1PRCF 4   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HAP1 1PRCF 5   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HAP1 1PRCF 6   0.000000E+00                                                     
HAP1 1PREFO1   1.00000   1.00000   0.00000   0.00000   1.00000   NN    0        
HAP1 1RADDAM    0.00000E+00    N    0      0.00                                 
HST  1  HNAM  Dummy histogram data set                                          
HST  1  IFIL  par_file.par                                                      
HST  1 BANK     1                                                               
HST  1 CHANS         0         1         0         1      2996                  
HST  1 DUMMY      2996  SLOG       1000.00  30000.00  0.001000                  
HST  1 EPHAS    0    0    0    0    0    0    0    0    0    Y                  
HST  1 ICONR   5664.98     -3.55     -8.29                                      
HST  1 ICONS   5664.98     -3.55     -8.29                                      
HST  1 NEXC     2                                                               
HST  1 NPHAS    1    0    0    0    0    0    0    0    0                       
HST  1 NREF     0    0.1780    N                                                
HST  1ABSCOR   0.000000E+00   0.000000E+00    N    0                            
HST  1BAKGD     4    4    Y    0    Y                                           
HST  1BAKGD1   0.100000E+01                                                     
HST  1BNKPAR     0.742    90.000      0.00    .00000     .3000    1    1        
HST  1CHI      90.0000                                                          
HST  1EXC  1     0.000     0.999                                                
HST  1EXC  2    20.020                                                          
HST  1HSCALE     10000.        Y    0                                           
HST  1I ITYP    0    1.000    20.000       9                                    
HST  1OMEGA     0.0000                                                          
HST  1PHI       0.0000                                                          
HST  1PRCF1     3   21   0.00500                                                
HST  1PRCF11   0.425565E+00   0.263286E-01   0.296905E-01   0.404614E+02        
HST  1PRCF12   0.404614E+02   0.000000E+00   0.000000E+00   0.529470E+01        
HST  1PRCF13   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HST  1PRCF14   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HST  1PRCF15   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HST  1PRCF16   0.000000E+00                                                     
ZZZZZZZZZZZZ  Last EXP file record                                              
